### ISSUE TITLE
Add FY24 holiday & special days

### ISSUE THREAD

**Issue by antshpra** [Zero65Tech/indian-stock-market#14]

**Comment by jaigupta04** [comment]
fy24 holidays added
special days pending
ref link - https://zerodha.com/z-connect/traders-zone/holidays/trading-and-market-holiday-calendar-2024-nse-bse-and-mcx

**Comment by antshpra** [comment]
Create a pull request and get the code reviewed from Rahul.

**Comment by jaigupta04** [comment]
it is already reviewed by Rahul

**Comment by antshpra** [comment]
He did not "approved" it yet.
